### ISSUE TITLE
SignUp

### ISSUE THREAD

**Issue by moria0525** [moria0525/MadeinJLM-students#14]
## User Story:
- As a User
- I want SignUp to system.
- So that I can create a profile to find work
### Expected behaviour

Should put on register and send an activation e-mail to the user
### Actual behaviour

Sends an email, but link of activation is broken.
### Steps to reproduce the behaviour

Coding and tests.
## Project Submission

Checklist:
- [x] Test feature scenarios
- [x] Update iteration page
  - [x] Iteration retospective
  - [x] Client review
  - [x] Update issues
  - [x] Application of course materials
- [x] git tag
- [x] Open page for next iteration 
  - [x] Plan issues
- [x] All engineers fill the peer-review 
- [x] Submit (message in chat room, assign this issue to checker)

**Comment by alonshmilo** [comment]
Is not connected to the right cpanel

**Comment by alonshmilo** [comment]
Activated mail is not working - the link returns an error

**Comment by alonshmilo** [comment]
Bug fixed

**Comment by alonshmilo** [comment]
Finish ✔️
