### ISSUE TITLE
Change Activation Status

### ISSUE THREAD

**Issue by alonshmilo** [moria0525/MadeinJLM-students#19]
## User Story:
- As a User
- I want to change my activation status
- So that companies and the organisation will know if I am looking for a job or not. 
### Expected behaviour
- Clicking on the button in the profile page turns the user from active to non-active.
### Actual behaviour
- After log out the button returns to the default. Data base is updated.
### Steps to reproduce the behaviour
- handling api and services

**Comment by alonshmilo** [comment]
Button returns to default after log out.

**Comment by sh00ki** [comment]
fixed :D !
