### ISSUE TITLE
project3-srs-submission

### ISSUE THREAD

**Issue by alonshmilo** [moria0525/MadeinJLM-students#2]
@ItamarShDev 
This is the submission of group-task # 3 - SRS.
A link to the [wiki-page](https://github.com/moria0525/MadeinJLM-students/wiki/SRS)
In this page there is a link to the pdf file which is the result of the SRS process we have worked for in the past week, and a link to the review results which will take place tomorrow at class.
The review results will also be submitted in this Issue page.
We have also submitted the first mockup screens of our project.
Thank you and goodnight,
MadeinJLM-for-students Team.

**Comment by Dor-H** [comment]
@ItamarShDev 
Review result:
Resubmission of group-task # 3 - SRS.
 [wiki-page](https://github.com/moria0525/MadeinJLM-students/wiki/SRS)
In the wiki page there is a link to the pdf file version 1.1 which is the result of the customer and teacher review.

MadeinJLM-for-students Team.

**Comment by ItamarShDev** [comment]
great!
