### ISSUE TITLE
Class Student

### ISSUE THREAD

**Issue by moria0525** [moria0525/MadeinJLM-students#20]
## Feature:
- [Login](https://github.com/moria0525/MadeinJLM-students/issues/11)
- [SignUp](https://github.com/moria0525/MadeinJLM-students/issues/14)
- [Forgeot Password](https://github.com/moria0525/MadeinJLM-students/issues/17)
- [Activation Mail](https://github.com/moria0525/MadeinJLM-students/issues/15)
- [Change Password](https://github.com/moria0525/MadeinJLM-students/issues/18)
- [Change Activation Status](https://github.com/moria0525/MadeinJLM-students/issues/19)
- List of programming languages (as combo box)
- List of skills (as combo box)
## Project Submission

Checklist:
- [x] Test feature scenarios
- [x] Update iteration page
  - [x] Iteration retospective
  - [x] Client review
  - [x] Update issues
  - [x] Application of course materials
- [x] git tag
- [x] Open page for next iteration 
  - [x] Plan issues
- [x] All engineers fill the peer-review 
- [x] Submit (message in chat room, assign this issue to checker)

**Comment by alonshmilo** [comment]
Finish 👍
