### ISSUE TITLE
Editing data in Student Table 

### ISSUE THREAD

**Issue by moria0525** [moria0525/MadeinJLM-students#29]
## Feature: Editing data in Student Table
- [Delete or Add skills to Student](https://github.com/moria0525/MadeinJLM-students/issues/24)
- [Delete or Add programming languages to Student](https://github.com/moria0525/MadeinJLM-students/issues/25)
- [Delete or Add recommendation to Student ](https://github.com/moria0525/MadeinJLM-students/issues/26)
- [Delete or Add 'Career portfolio' to Student](https://github.com/moria0525/MadeinJLM-students/issues/27)

**Comment by alonshmilo** [comment]
Done 👍
