### ISSUE TITLE
Iteration 3 - PES

### ISSUE THREAD

**Issue by alonshmilo** [moria0525/MadeinJLM-students#34]
#### Checklist:
- [x] Feature scenarios/tests passing
- [x] Iteration page updated, including:
  - [x] Iteration retrospective
  - [x] Client review
  - [x] Issues updates
  - [x] Section on application of course materials
- [x] git tag
- [x] Next iteration:
  - [x] Open page
  - [x] Select stories and plan issues
  - [x] Test scenarios
- [x] All engineers filled peer-review 
- [x] Submitted
  - [x] Announcement in chat room
  - [x] Assign this issue to checker
  - [x] Register for a review meeting

**Comment by alonshmilo** [comment]
Done 👍

**Comment by robi-y** [comment]
Was it reviewed and graded?

**Comment by alonshmilo** [comment]
@robi-y Not yet, it is not completed, will be completed by the end of the day, and will be announced in chat room, and in the submission issue #49

**Comment by alonshmilo** [comment]
And will be reviewed tomorrow with Itamar, we registered. 👍

**Comment by robi-y** [comment]
I thouht this was the submission issue... good luck
בתאריך 30 במאי 2016 08:36,‏ "alonshmilo" notifications@github.com כתב:
