### ISSUE TITLE
project6-Iteration 1 MVP-submission 

### ISSUE THREAD

**Issue by alonshmilo** [moria0525/MadeinJLM-students#42]
#### Checklist, e.g.,:
- [x] Feature scenarios/tests passing
- [x] Iteration page updated, including:
  - [x] Iteration retrospective
  - [x] Client review
  - [x] Issues updates
  - [x] Section on application of course materials
- [x] git tag
- [x] Next iteration:
  - [x] Open page
  - [x] Select stories and plan issues
  - [x] Test scenarios
- [x] All engineers filled peer-review 
- [x] Submitted
  - [x] Announcement in chat room
  - [x] Assign this issue to checker
  - [x] Register for a review meeting

**Comment by ItamarShDev** [comment]
- i dont see any retro perspective about the goals made and the actual result.
- i dont see testing reference
- i dont see code reviews

**Comment by alonshmilo** [comment]
Hi @ItamarShDev ,
- Retro perspective was added in iteration page.
- Tests were learned only last week in lecture in class, the day the iteration was done.
- Nobody talked about it until now. Today, due to your comment, I discussed with Reuven about it, and he will talk about it in class. Plus, it will be taken care of shortly anyway.

**Comment by alonshmilo** [comment]
Hi @ItamarShDev ,
Due to what we have discussed, what do we need to improve?

**Comment by ItamarShDev** [comment]
:+1:

**Comment by alonshmilo** [comment]
Hi @ItamarShDev, as we discussed, our grade is weird. Your help is wanted, thank you
