### ISSUE TITLE
Last finish

### ISSUE THREAD

**Issue by alonshmilo** [moria0525/MadeinJLM-students#48]
Last finish list:
- [x] Correct spelling
- [x] Syntax
- [x] Coding conventions
- [x] DB updated
- [x] Terms of use final wording
- Please add more checks

**Comment by Think-Smart** [comment]
@alonshmilo Please make sure the documentation is enough

**Comment by alonshmilo** [comment]
Ok @Think-Smart thank you

**Comment by Think-Smart** [comment]
@alonshmilo You are the best :kissing_heart:

**Comment by alonshmilo** [comment]
Done 👍
