### ISSUE TITLE
User/developer manual

### ISSUE THREAD

**Issue by alonshmilo** [moria0525/MadeinJLM-students#50]
- As a user
- I want to know how to use the app
- So that I will make the best of it

and...
- As a developer
- I want to know how to develop the app
- So that I will take care of it

**Comment by robi-y** [comment]
cute. remove the bug template..
בתאריך 30 במאי 2016 16:36,‏ "alonshmilo" notifications@github.com כתב:

**Comment by Dor-H** [comment]
@robi-y Removed, thank you. This is for the finals...

**Comment by moria0525** [comment]
i made user manual
@Think-Smart  and me - developer manual

**Comment by alonshmilo** [comment]
👍

**Comment by alonshmilo** [comment]
Done :+1:
