### ISSUE TITLE
project9-Iteration 4 SMF-submission

### ISSUE THREAD

**Issue by alonshmilo** [moria0525/MadeinJLM-students#51]
This is the submission of Iteration 4 and project summary. <br>
"Next iteration" was removed from the checklist, because it's the last iteration.
#### Checklist, e.g.,:
- [x] Feature scenarios/tests passing
- [x] Iteration page updated, including:
  - [x] Iteration retrospective
  - [x] Client review
  - [x] Issues updates
  - [x] Section on application of course materials
- [x] git tag
- [x] All engineers filled peer-review 
- [x] Submitted
  - [x] Announcement in chat room
  - [x] Assign this issue to checker
  - [x] Register for a review meeting

**Comment by alonshmilo** [comment]
Finishedddd 👍

**Comment by alonshmilo** [comment]
@ItamarShDev Hi Itamar, this is the submission of Iteration 4, to be presented today at 14:00

**Comment by alonshmilo** [comment]
@ItamarShDev All code files are in [this](https://github.com/moria0525/MadeinJLM-students/tree/master/mockup) folder

**Comment by ItamarShDev** [comment]
filled grades
